name: enviar correo automatico del mas tonto :p

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  enviar_correo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        architecture: "x64"
        cache: 'pip'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: enviar correo
      run: python el_mas_tonto.py ${{ secrets.LOGIN_EMAIL }} ${{ secrets.LOGIN_PASS }}
